export const dynamic = "force-dynamic";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from '../api/context/auth-context'
import { ThemeProvider } from "../api/context/theme-context";
import { MenuProvider } from "../api/context/menu-context";
import { ToastProvider } from "../api/context/toast-context"
import { Header } from "../components/header";
import { Footer } from "../components/footer";

import "./globals.css";
import { CustomerProvider } from "@/api/context/customer-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Synergi Healthtek",
  description: "Generated by create next app",
};

const fetchData = async () => {
  try {
    let [headerRes, footerRes] = await Promise.all([
      fetch(`${PORT}/api/navigation?populate=*`, { cache: "no-store" }),
      fetch(`${PORT}/api/footer?populate[logo]=true&populate[socials]=true&populate[menus]=true&populate[address][populate][emails]=true&populate[address][populate][phones]=true`, { cache: "no-store" })
    ]);

    let [headerData, footerData] = await Promise.all(
      [
        headerRes.json(),
        footerRes.json()
      ]
    );

    return [headerData.data, footerData.data];
  } catch (err) {
    console.log(err);
  }
};

export default async function RootLayout({ children }) {
  const [headerData, footerData] = await fetchData();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider>
          <ThemeProvider>
            <AuthProvider>
              <CustomerProvider>
                <MenuProvider>
                  <Header data={headerData} />
                  {children}
                  <Footer data={footerData} />
                </MenuProvider>
              </CustomerProvider>
            </AuthProvider>
          </ThemeProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
