import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from '../api/context/auth-context'
import { ThemeProvider } from "../api/context/theme-context";
import { MenuProvider } from "../api/context/menu-context";
import { ToastProvider } from "../api/context/toast-context"
import { Header } from "../components/header";
import { Footer } from "../components/footer";

import "./globals.css";
import { CustomerProvider } from "@/api/context/customer-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Synergi Healthtek",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider>
          <ThemeProvider>
            <AuthProvider>
              <CustomerProvider>
                <MenuProvider>
                  <Header />
                  {children}
                  <Footer />
                </MenuProvider>
              </CustomerProvider>
            </AuthProvider>
          </ThemeProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
