export const dynamic = "force-dynamic";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from '../api/context/auth-context'
import { ThemeProvider } from "../api/context/theme-context";
import { MenuProvider } from "../api/context/menu-context";
import { ToastProvider } from "../api/context/toast-context"
import { Header } from "../components/header";
import { Footer } from "../components/footer";

import "./globals.css";
import { CustomerProvider } from "@/api/context/customer-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Synergi Healthtek",
  description: "Generated by create next app",
};

const fetchHeaderFooter = async () => {
  const PORT = process.env.NEXT_PUBLIC_STRAPI_API_URL;
  try {
    const [headerRes, footerRes] = await Promise.all([
      fetch(`${PORT}/api/navigation?populate=*`, { cache: "no-store" }),
      fetch(`${PORT}/api/footer?populate[logo]=true&populate[socials]=true&populate[menus]=true&populate[address][populate][emails]=true&populate[address][populate][phones]=true`, { cache: "no-store" }),
    ]);

    const [header, footer] = await Promise.all([
      headerRes.json(),
      footerRes.json(),
    ]);
    console.log(header, footer)
    return [header, footer];
  } catch (err) {
    console.error("Error fetching header/footer:", err);
    return [null, null];
  }
};

export default async function RootLayout({ children }) {
  const [header, footer] = await fetchHeaderFooter();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider>
          <ThemeProvider>
            <AuthProvider>
              <CustomerProvider>
                <MenuProvider>
                  <Header data={header.data} />
                  {children}
                  <Footer data={footer.data} />
                </MenuProvider>
              </CustomerProvider>
            </AuthProvider>
          </ThemeProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
